language: objective-c
osx_image: xcode8
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install slather --no-ri --no-rdoc
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace Bulldog.xcworkspace -scheme Bulldog -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty;
  - pod lib lint;

after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash)
